name: checkcpu

jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: check all
        run: |
          echo $(nproc --all)
          echo $(free -h)
