name: Check
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Get Files
        uses: actions/checkout@main
        
      - name: check
        run: |
          ls
