name: Check
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: check
        run: |
          cd $GITHUB_WORKSPACE
          echo $PWD
